plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
  flog:
    enabled: true
  haml-lint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-67
  scss-lint:
    enabled: true