plugins:
  - react

extends:
  - 'eslint:recommended'
  - plugin:react/recommended

parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  impliedStrict: true

globals:
  Routes: true

settings:
  react:
    version: '16.2.0'

env:
  browser: true
  es6: true

rules:
  no-undef: error

  # React
  react/react-in-jsx-scope: error
  react/jsx-no-undef: error
  react/jsx-uses-vars: error
  react/jsx-key: error
  react/jsx-no-target-blank: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-comment-textnodes: error
  react/jsx-indent:
    - error
    - 2
  react/jsx-curly-spacing: error
  react/jsx-closing-tag-location: error
  react/jsx-closing-bracket-location:
    - error
    - selfClosing: after-props
      nonEmpty: after-props
  react/jsx-tag-spacing: error
  react/jsx-pascal-case: error
  react/jsx-wrap-multilines: error
  react/jsx-equals-spacing: error
  react/boolean-prop-naming: error
  react/default-props-match-prop-types: error
  react/jsx-boolean-value: error
  react/sort-prop-types: error
  react/sort-comp: error
  react/self-closing-comp: error

  semi: error
  no-unexpected-multiline: error
  no-extra-parens:
    - error
    - all
    - ignoreJSX: multi-line
  no-unsafe-negation: warn
  complexity:
    - warn
    - 4
  curly:
    - warn
    - all
  no-alert: error
  no-extra-bind: error
  no-eval: error
  radix:
    - error
    - always
  no-shadow: error

  prefer-const: error

  # Class Layout
  no-useless-constructor: error

  # Code style
  indent:
    - error
    - 2
  yoda:
    - warn
    - never
  brace-style:
    - error
    - 1tbs
  linebreak-style:
    - error
    - unix
  no-multi-spaces: error
  padded-blocks:
    - error
    - never
  spaced-comment: error
  semi-spacing: error
  keyword-spacing: error

  sort-keys: error
  eqeqeq: error
  no-floating-decimal: error
  dot-notation: error
  dot-location:
    - error
    - property

  # Control Flow
  max-depth:
    - error
    - 3

  no-implicit-coercion: error

  no-confusing-arrow: error
  space-infix-ops:
    - error
    - int32Hint: false
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never

  no-restricted-syntax:
    - error
    - selector: IfStatement > BinaryExpression[right.type='Literal'] > MemberExpression[property.name='name'] > MemberExpression[object.type='Identifier'][property.name='constructor']
      message: 'foo.prototype.name does always not survive minification. Use instanceof instead'
    - selector: CallExpression > MemberExpression[object.type='Identifier'][object.name='$'][property.type='Identifier'][property.name='extend']
      message: 'Prefer Object.assign or {... object} over jQuery $.extend as these methods are built-in to the browser.'
    - selector: CallExpression[callee.object.name='Object'][callee.property.name='assign'] > ObjectExpression:not(:matches([attr] > :first-child, :first-child))
      message: 'Prefer Object.assign({foo: bar}, ...) over Object.assign({}, {foo:bar}, ...) to reduce the number of objects created'
