AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 150

Style/BlockDelimiters:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

# Disabled because of
# lib/app/configuration.rb
# lib/app/instrumented_redis.rb
# app/support/security_policy.rb
MethodMissingSuper:
  Enabled: false

# Disabling because I wasn't able to get a certain association to work
Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/routes.rb'

# GOAL: Work to lower these limits
Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 150

# High Priority fix
Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Style/ClassAndModuleChildren:
  Enabled: false

# Going to assume it all works for Ruby 2.4
Style/FrozenStringLiteralComment:
  Enabled: false

# I've found this alarms way too much
Rails/InverseOf:
  Enabled: false

# Don't you tell me what to do!
Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/TimeZone:
 Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - assets

Style/GuardClause:
  MinBodyLength: 5

Rails/HasManyOrHasOneDependent:
  Enabled: false
