language: ruby
cache: bundler
services:
  - postgresql
addons:
  postgresql: '10.8'
before_script:
  - psql -c 'create database unit_tests;' -U postgres
  - cp config/database.yml.travis config/database.yml
