saltmaster:
  extends:
    file: common.yml
    service: saltmaster

saltminion:
  extends:
    file: common.yml
    service: saltminion
  links:
    - 'saltmaster:salt'

web:
  build: .
  command: bin/bundle exec bin/spring rails s -b 0.0.0.0 -p 8080 --pid /tmp/rails_s.pid
  volumes:
    - .:/rails-app
  expose:
    - 8080
  links:
    - 'saltmaster:salt'
    - 'redis:redis'
    - logstash
    - db
  volumes_from:
    - gems-2.1
  user: www-data
  environment:
    RAILS_ENV: development
    GEM_HOME: /gem-store

nginx:
  build: dockers/nginx
  ports:
    - 80
  links:
    - 'browsersync:web'
  environment:
    VIRTUAL_HOST: certmgr.devvm

redis:
  image: redis:3.0.2
  expose:
    - 6379

db:
  image: postgres:latest
  expose:
    - 5432
  environment:
    POSTGRES_PASSWORD: password12345

worker:
  build: .
  command: bin/bundle exec bin/rake resque:work
  volumes:
    - .:/rails-app
  volumes_from:
    - gems-2.1
  links:
    - 'saltmaster:salt'
    - 'redis:redis'
    - db
    - logstash
  environment:
    RAILS_ENV: development
    QUEUE: '*'

scheduler:
  extends:
    file: common.yml
    service: scheduler
  volumes:
    - .:/rails-app
  links:
    - 'redis:redis'
  environment:
    RAILS_ENV: development
    GEM_HOME: /gem-store

browsersync:
  build: dockers/browsersync
  command: start --proxy 'web:8080' --files '/app/app/**' --host 0.0.0.0 --port 8080 --no-notify
  links:
    - web
  expose:
    - 8080
  volumes:
    - .:/app:ro

logstash:
  build: dockers/logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  external_links:
    - elasticsearch
