saltmaster:
  extends:
    file: common.yml
    service: saltmaster

saltminion:
  extends:
    file: common.yml
    service: saltminion
  links:
    - 'saltmaster:salt'

web:
  extends:
    file: common.yml
    service: web
  volumes:
    - .:/rails-app
  links:
    - 'saltmaster:salt'
    - redis
  environment:
    RAILS_ENV: development
    VIRTUAL_HOST: certmgr.devvm

redis:
  image: redis
  expose:
    - 80

redis:
  image: redis:3.0
  ports:
    - 6379

worker:
  extends:
    file: common.yml
    service: worker
  volumes:
    - .:/rails-app
  links:
    - "saltmaster:salt"
    - redis
  environment:
    RAILS_ENV: development

scheduler:
  extends:
    file: common.yml
    service: scheduler
  volumes:
    - .:/rails-app
  links:
    - 'redis:redis'
  environment:
    RAILS_ENV: development

browsersync:
  image: browsersync
  command: "nodejs /usr/local/bin/browser-sync start --proxy 'web:3000' --files '/app/app/**' --host 0.0.0.0 --port 80"
  links:
    - web
  expose:
    - 80
  volumes:
    - .:/app:ro
  environment:
    VIRTUAL_HOST: certmgr-sync.devvm
