saltmaster:
  image: salt-master
  expose:
    - 8000
    - 4506
  ports:
    - "8080:8080"

saltminion:
  image: salt-minion
  links:
    - "saltmaster:salt"
  volumes:
    - /tmp/nginx/certs:/tmp/nginx/certs

web:
  build: .
  command: "/bin/sh -c 'rm -f tmp/pids/server.pid && rails s -b 0.0.0.0'"
  volumes:
    - .:/rails-app
  links:
    - "saltmaster:salt"
    - redis
  expose:
    - 3000
  environment:
    RAILS_ENV: development
    VIRTUAL_HOST: certmgr.devvm
  tty: true

redis:
  image: redis
  expose:
    - 6379

worker:
  build: .
  command: rake resque:work
  volumes:
    - .:/rails-app
  links:
    - "saltmaster:salt"
    - redis
  environment:
    RAILS_ENV: development
    QUEUE: "*"
    TERM_CHILD: 1

#scheduler:
#  build: .
#  command: rake resque:scheduler
#  volumes:
#    - .:/rails-app
#  environment:
#    RAILS_ENV: development
