saltmaster:
  extends:
    file: common.yml
    service: saltmaster

saltminion:
  extends:
    file: common.yml
    service: saltminion
  links:
    - 'saltmaster:salt'

web:
  image: rails
  command: bin/bundle exec bin/spring rails s -b 0.0.0.0 --pid /tmp/rails_s.pid
  volumes:
    - .:/rails-app
  links:
    - 'saltmaster:salt'
    - 'redis:redis'
  user: www-data
  environment:
    RAILS_ENV: development
  tty: true

nginx:
  build: dockers/nginx
  ports:
    - 80
  links:
    - 'browsersync:web'
  environment:
    VIRTUAL_HOST: certmgr.devvm

redis:
  image: redis:3.0
  expose:
    - 6379

worker:
  extends:
    file: common.yml
    service: worker
  volumes:
    - .:/rails-app
  links:
    - 'saltmaster:salt'
    - 'redis:redis'
  environment:
    RAILS_ENV: development

scheduler:
  extends:
    file: common.yml
    service: scheduler
  volumes:
    - .:/rails-app
  links:
    - 'redis:redis'
  environment:
    RAILS_ENV: development

browsersync:
  build: dockers/browsersync
  command: start --proxy 'web:3000' --files '/app/app/**' --host 0.0.0.0 --port 8080 --no-notify
  links:
    - web
  expose:
    - 8080
  volumes:
    - .:/app:ro
