redis: &redis_config
  host: redis
resque: redis:6379/resque
salt_stack:
  user: saltdev
  pass: saltdev
  eauth: auto
  host: http://salt:8000
session:
  - :redis_session_store
  -
    key: _CertManager_session
    httponly: true
    redis:
      host: redis
